version: 0.1.36
build:
    createdAt: "2026-04-06T02:59:54Z"
    git:
        branch: main
        commit: 0ce88c3025aeefdf86c6930053e321db3a418721
        tag: v0.1.36
        appCommit: 0ce88c3025aeefdf86c6930053e321db3a418721
    registry: your.azurecr.io
sources:
    releaseFlow:
        repo: https://github.com/Fremen-Labs/flume
        branch: main
        commit: 0ce88c3025aeefdf86c6930053e321db3a418721
        tag: v0.1.36
    app:
        repo: https://github.com/Fremen-Labs/flume
        commit: 0ce88c3025aeefdf86c6930053e321db3a418721
images:
    api:
        repository: api
        type: directory
        tag: 0.1.36
        path: .
        dockerfile: Dockerfile
        security:
            sbom: security/sbom/api-0.1.36.spdx.json.zst
            scan:
                tool: trivy
                resultFile: security/scans/api-0.1.36.trivy.json.zst
