version: 0.1.69
build:
    createdAt: "2026-04-14T21:56:23Z"
    git:
        branch: main
        commit: c2ec8fac7664eaaa00e491e448bc1cf89fe1fc71
        tag: v0.1.69
        appCommit: c2ec8fac7664eaaa00e491e448bc1cf89fe1fc71
    registry: your.azurecr.io
sources:
    releaseFlow:
        repo: https://github.com/Fremen-Labs/flume
        branch: main
        commit: c2ec8fac7664eaaa00e491e448bc1cf89fe1fc71
        tag: v0.1.69
    app:
        repo: https://github.com/Fremen-Labs/flume
        commit: c2ec8fac7664eaaa00e491e448bc1cf89fe1fc71
images:
    api:
        repository: api
        type: directory
        tag: 0.1.69
        path: .
        dockerfile: Dockerfile
        security:
            sbom: security/sbom/api-0.1.69.spdx.json.zst
            scan:
                tool: trivy
                resultFile: security/scans/api-0.1.69.trivy.json.zst
