version: 0.1.87
build:
    createdAt: "2026-04-27T20:47:21Z"
    git:
        branch: main
        commit: a6ed36a50cc8c4baaad890b4719f9e19357b53e5
        tag: v0.1.87
        appCommit: a6ed36a50cc8c4baaad890b4719f9e19357b53e5
    registry: your.azurecr.io
sources:
    releaseFlow:
        repo: https://github.com/Fremen-Labs/flume
        branch: main
        commit: a6ed36a50cc8c4baaad890b4719f9e19357b53e5
        tag: v0.1.87
    app:
        repo: https://github.com/Fremen-Labs/flume
        commit: a6ed36a50cc8c4baaad890b4719f9e19357b53e5
images:
    api:
        repository: api
        type: directory
        tag: 0.1.87
        path: .
        dockerfile: Dockerfile
        security:
            sbom: security/sbom/api-0.1.87.spdx.json.zst
            scan:
                tool: trivy
                resultFile: security/scans/api-0.1.87.trivy.json.zst
